/**
 * Created by chenty on 2016/10/19.
 */
export default {
    ic_call: require('./ic_call.png'),
    ic_back: require('./ic_back.png'),
    facility_1: require('./facility_1.png'),
    hotel_title: require('./facility_1.png'),
    choosed: require('./choosed.png'),
    unlimited: require('./unlimited.png'),
    search: require('./search.png'),
    sortListRight: require('./sortListRight.png'),
    nochecked: require('./nochecked.png'),
    right_arrow: require('./right_arrow@3x.png'),
    facility_wifi: require('./facility_wifi.png'),
    facility_num: require('./facility_num.png'),
    facility_bed: require('./facility_bed.png'),
    facility_floor: require('./facility_floor.png'),
    facility_square: require('./facility_square.png'),
    facility_window: require('./facility_window.png'),
    hotel_facilities_num: require('./hotel_facilities_num.png'),
    hotel_facilities_bed: require('./hotel_facilities_bed.png'),
    hotel_facilities_floor: require('./hotel_facilities_floor.png'),
    hotel_facilities_square: require('./hotel_facilities_square.png'),
    hotel_facilities_window: require('./hotel_facilities_window.png'),
    roomImg_none: require('./roomImg_none.png'),
    noInformation: require('./noInformation.png'),
    ic_clear: require('./ic_clear.png'),
    ic_up: require('./ic_up.png'),
    ic_hotel_map: require('./ic_hotel_map.png'),
    ic_hotel_address: require('./ic_hotel_address.png'),
    Rectangle: require('./Rectangle.png'),
    star: require('./start.png'),
    empty_star: require('./ic_empty_star.png'),
    ic_hotel_call: require('./ic_hotel_call.png'),
    ic_hotel_index_search_bg: require('./order_search_btn_normal.png'),
    ic_hotel_index_search_label: require('./ic_order_search_img.png'),
    ic_hotel_index_title_bar: require('./hotel_title.png'),
    ic_shenzhou_logo: require('./ic_shenzhou_logo.png'),
    ic_didi_logo: require('./ic_didi_logo.png'),
    ic_call_black: require('./ic_call_black.png'),
    layer_delete: require('./layer_delete.png'),
    ic_multiple_selected: require('./../../orderform/images/ic_multiple_selected.png'),
    ic_multiple_select: require('./../../orderform/images/ic_multiple_select.png'),
    ic_title_3point_new:require('./../../orderform/images/ic_title_3point_new.png'),
    ic_map_location: require('./ic_map_location.png'),
    ic_car_noselect: require('./ic_car_noselect.png'),
    ic_car_select: require('./ic_car_select.png'),
    ic_carmap: require('./ic_carmap.png'),
    ic_right_arrow_tint: require('./right_arrow_tint.png'),

}