/**
 * Created by shane on 17/4/12.
 */

// 定义调用入口组件
export const DEFINE_INITIAL_COMP = 'DEFINE_INITIAL_COMP';

// 订单详情页面loading
export const SHOW_EXPRESSAGE_ORDER_LOADING = 'SHOW_EXPRESSAGE_ORDER_LOADING';
// 获取订单详情
export const GET_EXPRESSAGE_ORDER = 'GET_EXPRESSAGE_ORDER';
// 取消订单
export const CANCEL_EXPRESSAGE_ORDER = 'CANCEL_EXPRESSAGE_ORDER';
// 重置订单详情数据
export const RESET_EXPRESSAGE_ORDER = 'RESET_EXPRESSAGE_ORDER';


// 订单列表显示状态
export const LIST_UPDATE_REQUEST_STATUS = 'LIST_UPDATE_REQUEST_STATUS';
// 订单列表显示数据
export const LIST_UPDATE_VIEW_DATA = 'LIST_UPDATE_VIEW_DATA';

//更新地址数据
export const UPDATE_ADDRESS_ITEM = 'UPDATE_ADDRESS_ITEM';

// 地址列表显示状态
export const ADDRESS_UPDATE_REQUEST_STATUS = 'ADDRESS_UPDATE_REQUEST_STATUS';
// 地址列表显示数据
export const ADDRESS_UPDATE_VIEW_DATA = 'ADDRESS_UPDATE_VIEW_DATA';

//更新新建订单数据
export const UPDATE_NEW_ORDER_ITEM = 'UPDATE_NEW_ORDER_ITEM';

//更新显示状态
export const UPDATE_EXPRESS_MODEL_VISIBLE = 'UPDATE_EXPRESS_MODEL_VISIBLE';

export const UPDATE_ADDRESS_DATA = 'UPDATE_ADDRESS_DATA';

export const QUERY_EXPRESS_PRICES = 'QUERY_EXPRESS_PRICES';

export const OPTION_ADDRESS_DATA = 'OPTION_ADDRESS_DATA';

export const QUERY_ARRIVE_TIME = 'QUERY_ARRIVE_TIME';

export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';

export const UPDATE_LOADING_VISIBLE = 'UPDATE_LOADING_VISIBLE';

export const UPDATE_ADDRESS_TITLE = 'UPDATE_ADDRESS_TITLE';

export const UPDATE_ADDRESS_FOR_PROPS = 'UPDATE_ADDRESS_FOR_PROPS';

export const CLOSE_MODAL_VISIBLE = 'CLOSE_MODAL_VISIBLE';

export const CLEAR_EXPRESS_STATE = 'CLEAR_EXPRESS_STATE';

export const COMPANY_ADDRESS = 'COMPANY_ADDRESS';

export const CLEAR_ADDRESS_STATE = 'CLEAR_ADDRESS_STATE';

export const UPDATE_ADDRESS_STREET_VISIBLE = 'UPDATE_ADDRESS_STREET_VISIBLE';

export const UPDATE_STREET_DATA = 'UPDATE_STREET_DATA';
