/**
 * Created by haosha on 16/9/5.
 */

export const TRIPS_TEST_DATA = [
    {
        "date": "2016-11-01",
        "items": [
            {
                "orderId": "",
                "status": 0,
                "from": {
                    "cityId": 95,
                    "city": "北京",
                    "time": "06:10",
                    "Date": "2016-11-01",
                    "latitude": "",
                    "address": "",
                    "longitude": ""
                },
                "canSubmit": false,
                "statusText": "",
                "enabled": true,
                "id": 1,
                "to": {
                    "city": "北京",
                    "Departterminalname": "T3",
                    "time": "06:10",
                    "longitude": 116.6162,
                    "cityId": 95,
                    "latitude": 40.05446,
                    "address": "首都机场",
                    "Date": "2016-11-01",
                    "DepartCityAirportCode": "PEK"
                },
                "pickUpResult": {
                    "passengerName": "王威",
                    "carGroupId": 2,
                    "carGroups": [{
                        "name": "公务轿车",
                        "startPrice": "128.0",
                        "kilometreUnitPrice": "4.0",
                        "freeTime": "0.0",
                        "timeUnitPrice": "0.6",
                        "freeDistance": "0.0",
                        "id": 2,
                        "desc": "大众帕萨特 丰田凯美瑞或类似5座车型"
                    }, {
                        "name": "商务7座",
                        "startPrice": "248.0",
                        "kilometreUnitPrice": "5.0",
                        "freeTime": "0.0",
                        "timeUnitPrice": "0.7",
                        "freeDistance": "0.0",
                        "id": 3,
                        "desc": "别克GL8或类似7座车型"
                    }, {
                        "name": "豪华轿车",
                        "startPrice": "288.0",
                        "kilometreUnitPrice": "5.5",
                        "freeTime": "0.0",
                        "timeUnitPrice": "1.0",
                        "freeDistance": "0.0",
                        "id": 4,
                        "desc": "奥迪A6 宝马5系或类似5座车型"
                    }],
                    "cityName": "北京",
                    "cityId": 1,
                    "serviceId": 8,
                    "serviceName": "送机",
                    "passengerMobile": "18501057627",
                    "carGroupType": "公务轿车"
                },
                "type": 1,
                "refId": 2
            },
            {
                "status": 0,
                "passengers": "707",
                "evening": {
                    "train": {
                        "seat_name": "二等座",
                        "to_station_type": "",
                        "train_no": "2400000G790B",
                        "type_code": "O",
                        "control_day": "",
                        "from": {
                            "cityId": 95,
                            "Date": "2016-11-01",
                            "station": "北京西",
                            "time": "10:00",
                            "stationCode": "",
                            "address": "北京",
                            "weatherInfo": {
                                "tempNight": "-1℃",
                                "conditionDay": "大部晴朗",
                                "weatherIdDay": "0",
                                "tempDay": "9℃/"
                            }
                        },
                        "sale_time": "",
                        "pubpritype": "pub",
                        "use_time": "483",
                        "note": "",
                        "to": {
                            "cityId": 518,
                            "Date": "2016-11-01",
                            "station": "广州南",
                            "time": "18:03",
                            "stationCode": "",
                            "address": "广州",
                            "weatherInfo": {
                                "tempNight": "18℃",
                                "conditionDay": "晴",
                                "weatherIdDay": "0",
                                "tempDay": "26℃/"
                            }
                        },
                        "can_web_buy": "Y",
                        "seat_bookable": 1,
                        "from_station": "北京西",
                        "to_station": "广州南",
                        "seat_price": 862,
                        "seat_yupiao": "351",
                        "companion": 1,
                        "to_time": "18:03",
                        "from_time": "10:00",
                        "shippingIndex": 4,
                        "from_station_type": "起点",
                        "train_number": "G79",
                        "day_diff": "0"
                    },
                    "flight": {
                        "TravelSupplierName": "易飞畅行",
                        "pubpritype": "pub",
                        "Departterminalname": "T2",
                        "ArriveCityAirportCode": "CAN",
                        "ArriveTime": "18:00",
                        "TPM": "1967",
                        "TMCIndex": 1,
                        "SeatNum": "A",
                        "PlaneType": "321",
                        "ClassName": "公务舱",
                        "AirportTax": 50,
                        "StopInfo": {},
                        "Airline": "CZ",
                        "VtWorkTime": "00:00-24:00",
                        "from": {
                            "cityID": 95,
                            "Date": "2016-11-01",
                            "station": "首都机场",
                            "time": "14:30",
                            "stationCode": "PEK",
                            "address": "北京",
                            "weatherInfo": {
                                "tempNight": "-1℃",
                                "conditionDay": "大部晴朗",
                                "weatherIdDay": "0",
                                "tempDay": "9℃/"
                            }
                        },
                        "RealPrice": 5730,
                        "Rebate": 0,
                        "FuelTax": 0,
                        "DepartCityAirportCode": "PEK",
                        "FlightNo": "CZ3162",
                        "TmcCode": "yifei",
                        "Arriveterminalname": "",
                        "IsBigCustomerPolicy": 0,
                        "travel_seconds": 12600,
                        "ClassCode": "J",
                        "TravelSupplierCode": "yifei",
                        "RealRebate": 0,
                        "ArriveCityAirportName": "新白云国际机场",
                        "to": {
                            "cityId": 518,
                            "Date": "2016-11-01",
                            "station": "新白云国际机场",
                            "time": "18:00",
                            "stationCode": "CAN",
                            "address": "广州",
                            "weatherInfo": {
                                "tempNight": "18℃",
                                "conditionDay": "晴",
                                "weatherIdDay": "0",
                                "tempDay": "26℃/"
                            }
                        },
                        "WorkTime": "00:00-24:00",
                        "shippingIndex": 1,
                        "StopNum": 0,
                        "DepartCityAirportName": "首都机场",
                        "Discount": 300,
                        "CarrierName": "南方航空",
                        "companion": 1,
                        "PrintPrice": 5730,
                        "use_time": 210,
                        "DepartTime": "14:30",
                        "YPrice": 1910,
                        "PolicyId": "0"
                    },
                    "hotel":{
                        distance: 990,
                        districtId: '0002',
                        hotelId: '40101022',
                        districtName: '东城区',
                        cityName: '北京',
                        businessZoneId: '010146',
                        cityId: 95,
                        hotelName: '北京贝尔特酒店',
                        businessZoneName: '',
                        address:'北京市王府井88号',
                        lowRate: 350,
                        thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                        review: {
                            count: '3647',
                            poor: '171',
                            good: '3436',
                            score: 0.96
                        },
                        startDate:'2016-11-12',
                        endDate:'2016-11-22',
                        days:9,
                        starRate: '3'
                    }
                },
                "flight": {
                    "TravelSupplierName": "易飞畅行",
                    "pubpritype": "pub",
                    "Departterminalname": "T3",
                    "ArriveCityAirportCode": "CAN",
                    "ArriveTime": "11:55",
                    "TPM": "1967",
                    "TMCIndex": 1,
                    "SeatNum": "A",
                    "PlaneType": "747",
                    "ClassName": "头等舱",
                    "AirportTax": 50,
                    "StopInfo": {},
                    "Airline": "CA",
                    "VtWorkTime": "00:00-24:00",
                    "from": {
                        "cityID": 95,
                        "Date": "2016-11-01",
                        "station": "首都机场",
                        "time": "08:40",
                        "stationCode": "PEK",
                        "address": "北京",
                        "weatherInfo": {
                            "tempNight": "-1℃",
                            "conditionDay": "大部晴朗",
                            "weatherIdDay": "0",
                            "tempDay": "9℃/"
                        }
                    },
                    "RealPrice": 2290,
                    "Rebate": 0,
                    "FuelTax": 0,
                    "DepartCityAirportCode": "PEK",
                    "FlightNo": "CA1321",
                    "TmcCode": "yifei",
                    "Arriveterminalname": "",
                    "IsBigCustomerPolicy": 0,
                    "travel_seconds": 11700,
                    "ClassCode": "A",
                    "TravelSupplierCode": "yifei",
                    "RealRebate": 0,
                    "ArriveCityAirportName": "新白云国际机场",
                    "to": {
                        "cityId": 518,
                        "Date": "2016-11-01",
                        "station": "新白云国际机场",
                        "time": "11:55",
                        "stationCode": "CAN",
                        "address": "广州",
                        "weatherInfo": {"tempNight": "18℃", "conditionDay": "晴", "weatherIdDay": "0", "tempDay": "26℃/"}
                    },
                    "WorkTime": "00:00-24:00",
                    "shippingIndex": 0,
                    "StopNum": 0,
                    "DepartCityAirportName": "首都机场",
                    "Discount": 120,
                    "CarrierName": "中国国航",
                    "companion": 1,
                    "PrintPrice": 2290,
                    "use_time": 195,
                    "DepartTime": "08:40",
                    "YPrice": 1910,
                    "PolicyId": "0"
                },
                "canSubmit": true,
                "statusText": 0,
                "selected": "flight",
                "departDate": "2016-11-01",
                "pubpritype": "pub",
                "morning": {
                    "train": {
                        "seat_name": "硬卧",
                        "to_station_type": "终点",
                        "train_no": "2400000Z3501",
                        "type_code": "3",
                        "control_day": "",
                        "from": {
                            "cityId": 95,
                            "Date": "2016-11-01",
                            "station": "北京西",
                            "time": "11:49",
                            "stationCode": "",
                            "address": "北京",
                            "weatherInfo": {
                                "tempNight": "-1℃",
                                "conditionDay": "大部晴朗",
                                "weatherIdDay": "0",
                                "tempDay": "9℃/"
                            }
                        },
                        "sale_time": "",
                        "pubpritype": "pub",
                        "use_time": "1281",
                        "note": "",
                        "to": {
                            "cityId": 518,
                            "Date": "2016-11-02",
                            "station": "广州",
                            "time": "09:10",
                            "stationCode": "",
                            "address": "广州",
                            "weatherInfo": {
                                "tempNight": "18℃",
                                "conditionDay": "晴",
                                "weatherIdDay": "0",
                                "tempDay": "26℃/"
                            }
                        },
                        "can_web_buy": "Y",
                        "seat_bookable": 1,
                        "from_station": "北京西",
                        "to_station": "广州",
                        "seat_price": 456,
                        "seat_yupiao": "244",
                        "companion": 1,
                        "to_time": "09:10",
                        "from_time": "11:49",
                        "shippingIndex": 6,
                        "from_station_type": "起点",
                        "train_number": "Z35",
                        "day_diff": "1"
                    },
                    "flight": {
                        "TravelSupplierName": "易飞畅行",
                        "pubpritype": "pub",
                        "Departterminalname": "T3",
                        "ArriveCityAirportCode": "CAN",
                        "ArriveTime": "11:55",
                        "TPM": "1967",
                        "TMCIndex": 1,
                        "SeatNum": "A",
                        "PlaneType": "747",
                        "ClassName": "头等舱",
                        "AirportTax": 50,
                        "StopInfo": {},
                        "Airline": "CA",
                        "VtWorkTime": "00:00-24:00",
                        "from": {
                            "cityID": 95,
                            "Date": "2016-11-01",
                            "station": "首都机场",
                            "time": "08:40",
                            "stationCode": "PEK",
                            "address": "北京",
                            "weatherInfo": {
                                "tempNight": "-1℃",
                                "conditionDay": "大部晴朗",
                                "weatherIdDay": "0",
                                "tempDay": "9℃/"
                            }
                        },
                        "RealPrice": 2290,
                        "Rebate": 0,
                        "FuelTax": 0,
                        "DepartCityAirportCode": "PEK",
                        "FlightNo": "CA1321",
                        "TmcCode": "yifei",
                        "Arriveterminalname": "",
                        "IsBigCustomerPolicy": 0,
                        "travel_seconds": 11700,
                        "ClassCode": "A",
                        "TravelSupplierCode": "yifei",
                        "RealRebate": 0,
                        "ArriveCityAirportName": "新白云国际机场",
                        "to": {
                            "cityId": 518,
                            "Date": "2016-11-01",
                            "station": "新白云国际机场",
                            "time": "11:55",
                            "stationCode": "CAN",
                            "address": "广州",
                            "weatherInfo": {
                                "tempNight": "18℃",
                                "conditionDay": "晴",
                                "weatherIdDay": "0",
                                "tempDay": "26℃/"
                            }
                        },
                        "WorkTime": "00:00-24:00",
                        "shippingIndex": 0,
                        "StopNum": 0,
                        "DepartCityAirportName": "首都机场",
                        "Discount": 120,
                        "CarrierName": "中国国航",
                        "companion": 1,
                        "PrintPrice": 2290,
                        "use_time": 195,
                        "DepartTime": "08:40",
                        "YPrice": 1910,
                        "PolicyId": "0"
                    },
                    "hotel":{
                        distance: 990,
                        districtId: '0002',
                        hotelId: '40101022',
                        districtName: '东城区',
                        cityName: '北京',
                        businessZoneId: '010146',
                        cityId: 95,
                        hotelName: '北京贝尔特酒店',
                        businessZoneName: '',
                        address:'北京市王府井88号',
                        lowRate: 350,
                        thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                        review: {
                            count: '3647',
                            poor: '171',
                            good: '3436',
                            score: 0.96
                        },
                        startDate:'2016-11-12',
                        endDate:'2016-11-22',
                        days:9,
                        starRate: '3'
                    }
                },
                "orderId": "",
                "visitors": "",
                "train": {
                    "seat_name": "硬卧",
                    "to_station_type": "终点",
                    "train_no": "2400000Z3501",
                    "type_code": "3",
                    "control_day": "",
                    "from": {
                        "cityId": 95,
                        "Date": "2016-11-01",
                        "station": "北京西",
                        "time": "11:49",
                        "stationCode": "",
                        "address": "北京",
                        "weatherInfo": {
                            "tempNight": "-1℃",
                            "conditionDay": "大部晴朗",
                            "weatherIdDay": "0",
                            "tempDay": "9℃/"
                        }
                    },
                    "sale_time": "",
                    "pubpritype": "pub",
                    "use_time": "1281",
                    "note": "",
                    "to": {
                        "cityId": 518,
                        "Date": "2016-11-02",
                        "station": "广州",
                        "time": "09:10",
                        "stationCode": "",
                        "address": "广州",
                        "weatherInfo": {"tempNight": "18℃", "conditionDay": "晴", "weatherIdDay": "0", "tempDay": "26℃/"}
                    },
                    "can_web_buy": "Y",
                    "seat_bookable": 1,
                    "from_station": "北京西",
                    "to_station": "广州",
                    "seat_price": 456,
                    "seat_yupiao": "244",
                    "companion": 1,
                    "to_time": "09:10",
                    "from_time": "11:49",
                    "shippingIndex": 6,
                    "from_station_type": "起点",
                    "train_number": "Z35",
                    "day_diff": "1"
                },
                "afternoon": {
                    "train": {
                        "seat_name": "一等座",
                        "to_station_type": "",
                        "train_no": "2400000G710A",
                        "type_code": "M",
                        "control_day": "",
                        "from": {
                            "cityId": 95,
                            "Date": "2016-11-01",
                            "station": "北京西",
                            "time": "07:40",
                            "stationCode": "",
                            "address": "北京",
                            "weatherInfo": {
                                "tempNight": "-1℃",
                                "conditionDay": "大部晴朗",
                                "weatherIdDay": "0",
                                "tempDay": "9℃/"
                            }
                        },
                        "sale_time": "",
                        "pubpritype": "pub",
                        "use_time": "574",
                        "note": "",
                        "to": {
                            "cityId": 518,
                            "Date": "2016-11-01",
                            "station": "广州南",
                            "time": "17:14",
                            "stationCode": "",
                            "address": "广州",
                            "weatherInfo": {
                                "tempNight": "18℃",
                                "conditionDay": "晴",
                                "weatherIdDay": "0",
                                "tempDay": "26℃/"
                            }
                        },
                        "can_web_buy": "Y",
                        "seat_bookable": 1,
                        "from_station": "北京西",
                        "to_station": "广州南",
                        "seat_price": 1380,
                        "seat_yupiao": "85",
                        "companion": 1,
                        "to_time": "17:14",
                        "from_time": "07:40",
                        "shippingIndex": 3,
                        "from_station_type": "起点",
                        "train_number": "G71",
                        "day_diff": "0"
                    },
                    "flight": {
                        "TravelSupplierName": "易飞畅行",
                        "pubpritype": "pub",
                        "Departterminalname": "T1",
                        "ArriveCityAirportCode": "CAN",
                        "ArriveTime": "12:20",
                        "TPM": "1967",
                        "TMCIndex": 1,
                        "SeatNum": "A",
                        "PlaneType": "787",
                        "ClassName": "头等舱",
                        "AirportTax": 50,
                        "StopInfo": {},
                        "Airline": "HU",
                        "VtWorkTime": "00:00-24:00",
                        "from": {
                            "cityID": 95,
                            "Date": "2016-11-01",
                            "station": "首都机场",
                            "time": "09:05",
                            "stationCode": "PEK",
                            "address": "北京",
                            "weatherInfo": {
                                "tempNight": "-1℃",
                                "conditionDay": "大部晴朗",
                                "weatherIdDay": "0",
                                "tempDay": "9℃/"
                            }
                        },
                        "RealPrice": 5730,
                        "Rebate": 0,
                        "FuelTax": 0,
                        "DepartCityAirportCode": "PEK",
                        "FlightNo": "HU7805",
                        "TmcCode": "yifei",
                        "Arriveterminalname": "",
                        "IsBigCustomerPolicy": 0,
                        "travel_seconds": 11700,
                        "ClassCode": "F",
                        "TravelSupplierCode": "yifei",
                        "RealRebate": 0,
                        "ArriveCityAirportName": "新白云国际机场",
                        "to": {
                            "cityId": 518,
                            "Date": "2016-11-01",
                            "station": "新白云国际机场",
                            "time": "12:20",
                            "stationCode": "CAN",
                            "address": "广州",
                            "weatherInfo": {
                                "tempNight": "18℃",
                                "conditionDay": "晴",
                                "weatherIdDay": "0",
                                "tempDay": "26℃/"
                            }
                        },
                        "WorkTime": "00:00-24:00",
                        "shippingIndex": 0,
                        "StopNum": 0,
                        "DepartCityAirportName": "首都机场",
                        "Discount": 300,
                        "CarrierName": "海南航空",
                        "companion": 1,
                        "PrintPrice": 5730,
                        "use_time": 195,
                        "DepartTime": "09:05",
                        "YPrice": 1910,
                        "PolicyId": "0"
                    },
                    "hotel":{
                        distance: 990,
                        districtId: '0002',
                        hotelId: '40101022',
                        districtName: '东城区',
                        cityName: '北京',
                        businessZoneId: '010146',
                        cityId: 95,
                        hotelName: '北京贝尔特酒店',
                        businessZoneName: '',
                        address:'北京市王府井88号',
                        lowRate: 350,
                        thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                        review: {
                            count: '3647',
                            poor: '171',
                            good: '3436',
                            score: 0.96
                        },
                        startDate:'2016-11-12',
                        endDate:'2016-11-22',
                        days:9,
                        starRate: '3'
                    }
                },
                "cityTo": "广州",
                "cityFrom": "北京",
                "companion": 1,
                "type": 2,
                "id": 2,
                "enabled": true,
                "refId": 0
            },
            {
                "orderId": "",
                "status": 0,
                "from": {
                    "city": "广州",
                    "Arriveterminalname": "",
                    "ArriveCityAirportCode": "CAN",
                    "address": "新白云国际机场",
                    "longitude": "",
                    "cityId": 518,
                    "latitude": "",
                    "time": "06:10",
                    "Date": "2016-11-01"
                },
                "canSubmit": false,
                "statusText": 0,
                "enabled": true,
                "id": 3,
                "to": {
                    "cityId": 518,
                    "city": "广州",
                    "time": "",
                    "Date": "",
                    "latitude": "",
                    "address": "",
                    "longitude": ""
                },
                "pickUpResult": {
                    "passengerName": "王威",
                    "carGroupId": 2,
                    "carGroups": [{
                        "name": "公务轿车",
                        "startPrice": "128.0",
                        "kilometreUnitPrice": "4.0",
                        "freeTime": "0.0",
                        "timeUnitPrice": "0.6",
                        "freeDistance": "0.0",
                        "id": 2,
                        "desc": "大众帕萨特 丰田凯美瑞或类似5座车型"
                    }, {
                        "name": "商务7座",
                        "startPrice": "248.0",
                        "kilometreUnitPrice": "5.0",
                        "freeTime": "0.0",
                        "timeUnitPrice": "0.7",
                        "freeDistance": "0.0",
                        "id": 3,
                        "desc": "别克GL8或类似7座车型"
                    }, {
                        "name": "豪华轿车",
                        "startPrice": "288.0",
                        "kilometreUnitPrice": "5.5",
                        "freeTime": "0.0",
                        "timeUnitPrice": "1.0",
                        "freeDistance": "0.0",
                        "id": 4,
                        "desc": "奥迪A6 宝马5系或类似5座车型"
                    }],
                    "cityName": "广州",
                    "cityId": 14,
                    "serviceId": 7,
                    "serviceName": "接机",
                    "passengerMobile": "18501057627",
                    "flightNo": "CA1321",
                    "carGroupType": "公务轿车"
                },
                "type": 3,
                "refId": 2
            },
            {
                id: 4,
                type: 4,
                canSubmit: true,
                statusText: 0,
                enabled: true,
                selected: "hotel",
                hotel:{
                    distance: 990,
                    districtId: '0002',
                    hotelId: '40101022',
                    districtName: '东城区',
                    cityName: '北京',
                    businessZoneId: '010146',
                    cityId: 95,
                    hotelName: '北京贝尔特酒店',
                    businessZoneName: '',
                    address:'北京市王府井88号',
                    lowRate: 350,
                    thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                    review: {
                        count: '3647',
                        poor: '171',
                        good: '3436',
                        score: 0.96
                    },
                    startDate:'2016-11-12',
                    endDate:'2016-11-22',
                    days:9,
                    starRate: '3'
                },
                "morning": {
                    type:4,
                    "hotel":{
                        distance: 990,
                        districtId: '0002',
                        hotelId: '40101022',
                        districtName: '东城区',
                        cityName: '北京',
                        businessZoneId: '010146',
                        cityId: 95,
                        hotelName: '北京贝尔特酒店',
                        businessZoneName: '',
                        address:'北京市王府井88号',
                        lowRate: 350,
                        thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                        review: {
                            count: '3647',
                            poor: '171',
                            good: '3436',
                            score: 0.96
                        },
                        startDate:'2016-11-12',
                        endDate:'2016-11-22',
                        days:9,
                        starRate: '3'
                    }
                },
                "afternoon": {
                    type:4,
                    "hotel":{
                        distance: 990,
                        districtId: '0002',
                        hotelId: '40101022',
                        districtName: '东城区',
                        cityName: '北京',
                        businessZoneId: '010146',
                        cityId: 95,
                        hotelName: '北京贝尔特酒店',
                        businessZoneName: '',
                        address:'北京市王府井88号',
                        lowRate: 350,
                        thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                        review: {
                            count: '3647',
                            poor: '171',
                            good: '3436',
                            score: 0.96
                        },
                        startDate:'2016-11-12',
                        endDate:'2016-11-22',
                        days:9,
                        starRate: '3'
                    }
                },
                "evening": {
                    type:4,
                    "hotel":{
                        distance: 990,
                        districtId: '0002',
                        hotelId: '40101022',
                        districtName: '东城区',
                        cityName: '北京',
                        businessZoneId: '010146',
                        cityId: 95,
                        hotelName: '北京贝尔特酒店',
                        businessZoneName: '',
                        address:'北京市王府井88号',
                        lowRate: 350,
                        thumbNailUrl: 'http://pavo.elongstatic.com/i/Hotel120_120/000062Lx.jpg',
                        review: {
                            count: '3647',
                            poor: '171',
                            good: '3436',
                            score: 0.96
                        },
                        startDate:'2016-11-12',
                        endDate:'2016-11-22',
                        days:9,
                        starRate: '3'
                    }
                },
            }
            ],

        "id": 1
    },

];

export const RCMD_TAXI_DATA = [
    {  // 送机信息
        'id': 10,
        'from': {  // 接机from是这样填吗，不是的话from信息从哪获取
            'time': '08:00',
            'address': '深圳宝安机场',
            'city': '深圳',
            'longitude': 0,
            'latitude': 0,
        },
        'to': {
            'time': '12:30',
            'address': '北京国际机场',
            'city': '北京',
            'longitude': 0,
            'latitude': 0,
        },
        'type': 1,  // 1.送机 2.火车/飞机 3.接机
        'total': 100,
        'refId': 11,  // 飞机票的id
        'orderId': 0,
        'status': 0,
        'enabled': false,
        'canSubmit': false,
    },
    {  // 接机信息
        'id': 12,
        'from': {  // 接机from是这样填吗，不是的话from信息从哪获取
            'time': '08:00',
            'address': '深圳宝安机场',
            'city': '深圳',
            'longitude': 0,
            'latitude': 0,
        },
        'to': {
            'time': '12:30',
            'address': '北京国际机场',
            'city': '北京',
            'longitude': 0,
            'latitude': 0,
        },
        'type': 3,  // 1.接机 2.火车/飞机 3.送机
        'total': 100,
        'refId': 11,  // 飞机票的id
        'orderId': 0,
        'status': 0,
        'enabled': false,
        'canSubmit': false,
    }
];